---
- name: Call hello world ansible roles
  hosts: all
  tasks:
  
    - name: Clone ansible role
      shell: ansible-galaxy install -r roles/requirements.yml -p roles/helloworld
      delegate_to: localhost
      
    - name: Execute ansible role
      include_role:
        name: helloworld
